/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Entity.Employee;
import Entity.Employee_Phones;
import Entity.Project;
import Entity.Workon;
import Entity.department;
import company.Tools;

/**
 *
 * @author omark
 */
public class frmtest extends javax.swing.JFrame {

    /**
     * Creates new form frmtest
     */
    public frmtest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btntest = new controls.JMyButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltest = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbltest1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnTestemp = new controls.JMyButton();
        btnphone = new controls.JMyButton();
        btnproject = new controls.JMyButton();
        btnproject1 = new controls.JMyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btntest.setText("Test Department");
        btntest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntestActionPerformed(evt);
            }
        });

        tbltest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbltest);

        tbltest1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbltest1);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnTestemp.setText("Test Employee");
        btnTestemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestempActionPerformed(evt);
            }
        });

        btnphone.setText("fromphone");
        btnphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnphoneActionPerformed(evt);
            }
        });

        btnproject.setText("frmproject");
        btnproject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprojectActionPerformed(evt);
            }
        });

        btnproject1.setText("frmworktest");
        btnproject1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproject1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btntest, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(btnTestemp, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(btnphone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnproject, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnproject1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(510, 510, 510)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btntest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnTestemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnproject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btnproject1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntestActionPerformed
        
        department dept = new department();
        
     
       //dept.setDeptno(2);
        //dept.setDeptName("omarkh");
       // dept.setLocation("tunis");
       // dept.add();
        //dept.update();
        //dept.delete();
        //dept.getAllRows(tbltest);
        //  Tools.MsgBox(dept.getAutoNumber());
         //dept.getCustomRows("select * from department ", tbltest);
         //dept.getOneRows(tbltest);
         //Tools.MsgBox(dept.getValueByName("omar"));
         //Tools.MsgBox(dept.getNameByValue("2"));
         
    }//GEN-LAST:event_btntestActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean conf = Tools.confirmMsg("hello omaryto");
        if(conf)  Tools.MsgBox("yes");
        else  Tools.MsgBox("other");
    }//GEN-LAST:event_jButton1ActionPerformed
         Employee emp = new Employee();
    private void btnTestempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestempActionPerformed
      /* emp.setEmpNO(4);
       
       emp.setEmpName("omarhhhh");
       emp.setAddress("tunihhhhhs");
       emp.setSalary(11.400);
       emp.setBirthDate("2019-08-01");
       emp.setHiringDate("2000-04-05");
       emp.setDeptno(1);
       emp.add();*/
       //emp.update();
       //emp.delete();
       //Tools.MsgBox(emp.getAutoNumber());
       //emp.getAllRows(tbltest);
       //emp.getCustomRows("select * from employee_data", tbltest);
       //Tools.MsgBox(emp.getNameByValue("2"));
       //Tools.MsgBox(emp.getValueByName("iyed khbouchi"));
       //emp.getOneRows(tbltest);
    }//GEN-LAST:event_btnTestempActionPerformed
 Employee_Phones phon = new Employee_Phones();
    private void btnphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnphoneActionPerformed
      
       //phon.setEmpNo(1);
       //phon.setPhone("01254718936");
       //phon.add();
       //phon.delete();
       //phon.deletByEmp();
      // phon.getAllRows(tbltest);
    }//GEN-LAST:event_btnphoneActionPerformed
Project proj = new Project();
    private void btnprojectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprojectActionPerformed
      //  proj.setProjectNo(2);
       // proj.setProjectName("Ndjjjjhhhjame");
        //proj.setLocation("Ljjjjhhd");
       // proj.setDeptno(2);
       // proj.add();
      // proj.update();
       //proj.delete();
      //  work.getAllRows(tbltest);
    }//GEN-LAST:event_btnprojectActionPerformed
  Workon work = new Workon();
    private void btnproject1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproject1ActionPerformed
        work.setEmpNo(1);
       work.setProjectNo(3);
        //work.add();
       // work.update();
       //work.delete();
      // work.getAllRows(tbltest);
    }//GEN-LAST:event_btnproject1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmtest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmtest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmtest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmtest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmtest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMyButton btnTestemp;
    private controls.JMyButton btnphone;
    private controls.JMyButton btnproject;
    private controls.JMyButton btnproject1;
    private controls.JMyButton btntest;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbltest;
    private javax.swing.JTable tbltest1;
    // End of variables declaration//GEN-END:variables
}
